### ISSUE TITLE
Make file tabs smaller

### ISSUE THREAD

**Issue by TomBarryy** [noahbuscher/Flatron#23]
Just installed, I like the theme. One feature I would like would be to customize the size of the file tabs. By default they are a bit larger than I would like. If possible it would be great if I could adjust them

**Comment by peterkos** [comment]
Within the `Flatron.sublime-theme` file, you can change the `row_padding` key within the `//SIDEBAR` section to whatever value you want.

The array follows the pattern `[side padding, height padding]`, and can be used as follows:

```
{
//...
"row_padding": [10, 6],
//...
```

**Comment by TomBarryy** [comment]
Ah I got it through the package manager (Sublime Text 3) and there is no Flatron.sublime-theme file. There is a Flatron.sublime-package file but it is not human readable

**Comment by noahbuscher** [comment]
Seems to be resolved... closing 😄
